# Generated by Django 4.2.1 on 2023-05-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
