# Generated by Django 4.2.1 on 2023-05-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='rating',
        ),
    ]
