# Generated by Django 4.2.1 on 2023-05-31 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_tag_advertisement_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
