# Generated by Django 4.2.1 on 2023-05-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_remove_advertisement_tags_delete_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
