# Generated by Django 4.2.1 on 2023-05-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
