# Generated by Django 4.2.1 on 2023-05-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instagram_link',
            field=models.URLField(blank=True, verbose_name='Instagram link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_link',
            field=models.URLField(blank=True, verbose_name='LinkedIn link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter_link',
            field=models.URLField(blank=True, verbose_name='Twitter link'),
        ),
    ]
