# Generated by Django 4.2.1 on 2023-05-31 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='languages',
        ),
    ]
