# Generated by Django 4.2.1 on 2023-05-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='rating',
            new_name='ratings',
        ),
    ]
